=== jdobmej0511/Lenguaje-de-marcas/unidad 01/ejercicios/ejercicio9.dtd
<!ELEMENT catalogo (libro+)>
<!ELEMENT libro (title,creator,fecha?,lanzamiento?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT creator (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT lanzamiento (#PCDATA)>

=== jdobmej0511/Lenguaje-de-marcas/unidad 01/ejercicios/ejercicio9.xml
<?xml version="1.0" encoding="UTF-8"?>

<<<<<<< HEAD
<!DOCTYPE catalogo SYSTEM "ejercicio9.dtd">
<catalogo xmlns:dc="http://purl.org/dc/elements/1.1/"
>
=======
<catalogo xmlns:dc="http://purl.org/dc/elements/1.1/">
>>>>>>> 50cbe1b2f956fa324e5899ad083413b6294f0e6e
    <libro>
        <dc:title>Mandanga estail</dc:title>
        <dc:creator>Juan FernÃ¡ndez</dc:creator>
        <fecha>25/05/2014</fecha>
    </libro>

    <libro>
        <dc:title>Cars</dc:title>
        <dc:creator>Rayo McQueen</dc:creator>
        <lanzamiento>05/11/2006</lanzamiento>
    </libro>
</catalogo>
